version: '3.8'

services:
  # MinIO (armazenamento S3 local)
  minio:
    image: minio/minio:latest
    container_name: minio_server
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_REDIRECT_URL: "http://localhost:9001"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - pcmetrics_net

  # Airflow
  airflow:
    image: apache/airflow:2.7.1
    container_name: airflow_server
    restart: always
    depends_on:
      - minio
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__FERNET_KEY: "YOUR_FERNET_KEY" # gerar com `python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"`
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "sqlite:////root/airflow/airflow.db"
      AIRFLOW__CORE__DAGS_FOLDER: "/root/airflow/dags"
    volumes:
      - ./dags:/root/airflow/dags
      - ./logs:/root/airflow/logs
    ports:
      - "8080:8080"
    command: bash -c "airflow db init && airflow webserver & airflow scheduler"
    networks:
      - pcmetrics_net

networks:
  pcmetrics_net:
    driver: bridge
